### ISSUE TITLE
Dataset access of UCR_TS_Archive_2015

### ISSUE THREAD

**Issue by anindyasarkarIITH** [hfawaz/ijcnn19attacks#1]
Hi,
    I have downloaded "https://www.cs.ucr.edu/~eamonn/time_series_data/UCR_TS_Archive_2015.zip" . But  it needs password while extracting. I don't have required passwored. Can you please send the entire data to my mail id ( anindyasarkar.ece@gmail.com).
It will be a big help for me.

**Comment by hfawaz** [comment]
Hi, 

You can find the description (and the hidden password) here: https://www.cs.ucr.edu/~eamonn/time_series_data/UCR%20Time%20Series%20Classification%20Archive.pdf

The password is a challenge ;) 

Good luck
